fastlane_version "2.28.5"

default_platform :ios

platform :ios do

### Preparation and error lanes

    before_all do |lane, options|
      update_fastlane
      sh "security list-keychain -s /Library/Developer/XcodeServer/Keychains/Portal.keychain ~/Library/Keychains/login.keychain-db /Library/Keychains/System.keychain"
      sh "security unlock-keychain -p `cat /Library/Developer/XcodeServer/SharedSecrets/PortalKeychainSharedSecret` /Library/Developer/XcodeServer/Keychains/Portal.keychain"
    end

    error do |lane, exception, options|
      if !String(lane).include? "dsyms" and !String(lane).include? "playground" # ignore dsyms-related and playground lanes
        slack(
                   message: "Failure: #{exception.message}",
                   success: false,
                 slack_url: "https://hooks.slack.com/services/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",
             )
       end
    end

### Utility lanes

  lane :playground do # for testing purposes

  end

  lane :upload_last_dsyms do # scheduled as a cronjob
    download_dsyms(
          build_number: String(latest_testflight_build_number),
        )
    upload_symbols_to_sentry(
        auth_token: '7650c06ce93c44f6bd57bdc29f2c03cf48f1916ab27c4bab98c746ada902caf3',
        org_slug: 'hidoc',
        project_slug: 'cara-rn',
                            )
    clean_build_artifacts
  end

  lane :refresh_dsyms do # takes a loooong time
    download_dsyms
    upload_symbols_to_sentry(
        auth_token: '7650c06ce93c44f6bd57bdc29f2c03cf48f1916ab27c4bab98c746ada902caf3',
        org_slug: 'hidoc',
        project_slug: 'cara-rn',
                            )
    clean_build_artifacts
  end

end
